- name: Add Google Chrome GPG key securely
  ansible.builtin.get_url:
    url: https://dl.google.com/linux/linux_signing_key.pub
    dest: /usr/share/keyrings/google-linux-signing-key.pub
    mode: '0644'
    force: true
    validate_certs: true

- name: apt-key add for other tools
  apt_key:
    url: "{{ item.url }}"
    state: "{{ item.state }}"
  loop:
    - { state: "present", url: "https://download.docker.com/linux/ubuntu/gpg" }
    - { state: "present", url: "https://apt.corretto.aws/corretto.key" }

- name: Add Google Chrome APT repository
  apt_repository:
    repo: "deb [arch=amd64 signed-by=/usr/share/keyrings/google-linux-signing-key.pub] http://dl.google.com/linux/chrome/deb/ stable main"
    state: present
    filename: google-chrome

- name: Add Docker and Corretto APT repositories
  apt_repository:
    repo: "{{ item.repo }}"
    state: "{{ item.state }}"
  loop:
    - { state: "present", repo: "deb [arch=amd64] https://download.docker.com/linux/ubuntu jammy stable" }
    - { state: "present", repo: "deb [arch=amd64] https://apt.corretto.aws stable main" }
