- name: Get latest NVM version from GitHub
  ansible.builtin.shell: |
    curl -s https://api.github.com/repos/nvm-sh/nvm/releases/latest | grep tag_name | cut -d '"' -f4
  register: nvm_version
  changed_when: false

- name: Clone latest NVM to /tmp as wsansible
  ansible.builtin.shell: |
    git clone --depth=1 https://github.com/nvm-sh/nvm.git /tmp/nvm
    cd /tmp/nvm && git checkout {{ nvm_version.stdout }}
  args:
    creates: /tmp/nvm
  become: true
  become_user: wsansible

- name: Get list of user home directories
  ansible.builtin.find:
    paths: /home
    file_type: directory
    recurse: false
  register: home_dirs

- name: Copy NVM to each user's home directory
  ansible.builtin.copy:
    src: /tmp/nvm/
    dest: "{{ item.path }}/.nvm/"
    owner: "{{ item.path | basename }}"
    group: "{{ item.path | basename }}"
    mode: '0755'
  loop: "{{ home_dirs.files }}"
  become: true

- name: Add NVM to each user’s .bashrc
  ansible.builtin.blockinfile:
    path: "{{ item.path }}/.bashrc"
    marker: "# {mark} ANSIBLE MANAGED BLOCK: NVM"
    block: |
      export NVM_DIR="$HOME/.nvm"
      [ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"
  loop: "{{ home_dirs.files }}"
  become: true
