- name: Get latest NVM version
  ansible.builtin.shell: |
    curl -s https://api.github.com/repos/nvm-sh/nvm/releases/latest \
    | grep '"tag_name":' | cut -d '"' -f4
  register: nvm_version
  changed_when: false

- name: Find user home directories in /home
  ansible.builtin.find:
    paths: /home
    file_type: directory
    recurse: no
  register: home_dirs

- name: Clone NVM repo using shell (avoid git module issues)
  ansible.builtin.shell: |
    git clone --depth=1 --branch {{ nvm_version.stdout }} https://github.com/nvm-sh/nvm.git "{{ item.path }}/.nvm"
  args:
    executable: /bin/bash
  become: true
  become_user: "{{ item.path | basename }}"
  loop: "{{ home_dirs.files }}"


- name: Append NVM environment variables to .bashrc
  ansible.builtin.lineinfile:
    path: "{{ item.path }}/.bashrc"
    line: |
      export NVM_DIR="$HOME/.nvm"
      [ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"
    insertafter: EOF
    create: yes
    state: present
  loop: "{{ home_dirs.files }}"

- name: Install latest Node.js using NVM
  ansible.builtin.shell: |
    export NVM_DIR="$HOME/.nvm"
    [ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"
    nvm install node
  args:
    executable: /bin/bash
  become: true
  become_user: "{{ item.path | basename }}"
  loop: "{{ home_dirs.files }}"
