apiVersion: apps/v1
kind: Deployment
metadata:
  name: bedrock-gw-1
  namespace: bedrock-gw
spec:
  replicas: 1
  selector:
    matchLabels:
      app: api
  template:
    metadata:
      labels:
        app: api
    spec:
      serviceAccountName: bedrock-gw-cross-1
      containers:
      - name: api
        image: 281904313825.dkr.ecr.us-east-1.amazonaws.com/bedrock-gw:api-0.7
        ports:
        - containerPort: 80
        env:
        - name: DB_HOST
          valueFrom:
            configMapKeyRef:
              name: bedrock-gw-config
              key: DB_HOST
        - name: DB_NAME
          valueFrom:
            configMapKeyRef:
              name: bedrock-gw-config
              key: DB_NAME
        - name: DB_PORT
          valueFrom:
            configMapKeyRef:
              name: bedrock-gw-config
              key: DB_PORT
        - name: DB_USER
          valueFrom:
            secretKeyRef:
              name: bedrock-gw-secrets
              key: DB_USER
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: bedrock-gw-secrets
              key: DB_PASSWORD
