apiVersion: v1
kind: Secret
metadata:
  name: bedrock-gw-secrets
  namespace: bedrock-gw
type: Opaque
data:
  DB_USER: "YmFzZTY0LWVuY29kZWQtdXNlcm5hbWU="  # base64-encoded username
  DB_PASSWORD: "YmFzZTY0LWVuY29kZWQtcGFzc3dvcmQ="  # base64-encoded password
