name: Workspace Maintenance Pipeline

on:
  workflow_dispatch:

jobs:
  rebuild-and-baseline:
    runs-on: [self-hosted]
    defaults:
      run:
        working-directory: ./rebuild/ubuntu/

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Rebuild all Workspaces
        run: ./scripts/rebuild_all.sh

      - name: Wait for Workspaces to Become Available
        run: ./scripts/wait_for_all_available.sh

      - name: Run Baseline on all Workspaces
        run: ./scripts/run_baseline.sh

      - name: Generate HTML Report
        run: python3 ./scripts/generate_html_report.py

      - name: Send Email with Report via SNS
        run: ./scripts/send_email.sh
