name: Rebuild AWS Workspace and Run Baseline

on:
  workflow_dispatch:  # Manual trigger

jobs:
  rebuild-workspace:
    runs-on: gha-fdp-backhead

    permissions:
      id-token: write
      contents: read

    env:
      WORKSPACE_ID: ws-xxxxxxxxx
      REGION: us-east-1          

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4

    - name: Configure AWS credentials via OIDC
      uses: aws-actions/configure-aws-credentials@v2
      with:
        role-to-assume: arn:aws:iam::123456789012:role/github-action-role
        aws-region: ${{ env.REGION }}

    - name: Rebuild Workspace
      run: |
        echo "Starting rebuild of workspace $WORKSPACE_ID"
        aws workspaces rebuild-workspace --workspace-id "$WORKSPACE_ID"
        echo "Workspace rebuild initiated."

    - name: Wait for Workspace to become AVAILABLE
      run: |
        echo "Waiting for workspace $WORKSPACE_ID to become AVAILABLE..."
        while true; do
          STATUS=$(aws workspaces describe-workspaces --workspace-ids "$WORKSPACE_ID" --query 'Workspaces[0].State' --output text)
          echo "Current Status: $STATUS"
          if [[ "$STATUS" == "AVAILABLE" ]]; then
            break
          fi
          sleep 30
        done
        echo "Workspace is now AVAILABLE."

    - name: Run Baseline Script (run_user.sh)
      run: |
        echo "Running baseline script..."
        chmod +x ./run_user.sh
        ./run_user.sh
