jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up SSH key
        run: |
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > key.pem
          chmod 600 key.pem

      - name: Install expect
        run: sudo apt-get update && sudo apt-get install -y expect

      - name: Run Ansible script with vault password
        run: |
          expect <<EOF
          spawn ./deploy.sh
          expect "Vault password:"
          send "${{ secrets.ANSIBLE_VAULT_PASSWORD }}\r"
          expect eof
          EOF
